name: "Terraform"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # O pipeline só aciona se houver mudança na pasta terraform
  workflow_dispatch: # Permite disparar manualmente

permissions:
  contents: read
  id-token: write # Permite que o GitHub gere o token para falar com o GCP

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform # Comandos vão rodar na pasta do terraform

    steps:
    # 1. Baixa código para a máquina do GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Autentica no Google usando a Federação
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        # Url do identity provider
        workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
        
        # sv
        service_account: ${{secrets.SERVICEACCOUNT}}

    # 3. Instala o Terraform na máquina
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 4. Inicia o Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Plan
    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        TF_VAR_project_id: ${{ secrets.PROJECT_ID }}

    # 6. Appy
    - name: Terraform Apply
      # Só roda o apply se estivermos na branch main e for um push
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      env:
        TF_VAR_project_id: ${{ secrets.PROJECT_ID }}